# BEGIN_KITTY_THEME
# Gruvbox Dark Soft
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family="SF Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size 11
macos_thicken_font 0.1

modify_font cell_height 5px
modify_font underline_position 1

tab_bar_style fade
tab_bar_edge top
tab_fade 0

tab_bar_margin_width	0
tab_bar_margin_height   0 0

tab_title_template          "{fmt.bg.default}{fmt.fg._cccccc} {title} {fmt.fg.default}{fmt.fg.default}"
active_tab_title_template   "{fmt.bg._3e9742}{fmt.fg._f8f8f8} {title} {fmt.fg.default}{fmt.fg.default}"
