vim.keymap.set({ 'n', 'v' }, '<leader>cc', ':CopilotChatToggle<CR>')
vim.keymap.set({ 'n', 'v' }, '<leader>ce', ':CopilotChatExplain<CR>')
vim.keymap.set({ 'n', 'v' }, '<leader>ct', ':CopilotChatTests<CR>')
vim.keymap.set({ 'n', 'v' }, '<leader>cr', ':CopilotChatReview<CR>')
vim.keymap.set({ 'n', 'v' }, '<leader>cf', ':CopilotChatFix<CR>')
vim.keymap.set({ 'n', 'v' }, '<leader>cm', ':CopilotChatCommit<CR>')