require("config.lazy")
require("config.basic")
require("config.git")
require("config.copilot")
require("config.oil")
require("config.lsp")
require("config.trim")
require("config.barbar")
require("config.wrap")

require("config.theme")
